//Configuring the songs produces quite a lot of data, so I split it into separate categories.
#include "songs_config_01_names.h"
#include "songs_config_02_infos.h"
#include "songs_config_03_scenenames.h"
#include "songs_config_04a_scenes.h"
#include "songs_config_04b_scenes.h"
#include "songs_config_04c_scenes.h"
#include "songs_config_04d_scenes.h"
#include "songs_config_05_switches.h"
#include "songs_config_06_switchesmode.h"
#include "songs_config_07_internal_potis_function.h"
#include "songs_config_08_internal_potis_direction.h"
#include "songs_config_09_external_potis_function.h"
#include "songs_config_10_external_potis_direction.h"
